// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/aether.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_proto_aether_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_proto_aether_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *DataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_aether_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerCount     int32                  `protobuf:"varint,1,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	LastBlockHash string                 `protobuf:"bytes,2,opt,name=last_block_hash,json=lastBlockHash,proto3" json:"last_block_hash,omitempty"`
	TotalBlocks   int32                  `protobuf:"varint,3,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_aether_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *StatusResponse) GetLastBlockHash() string {
	if x != nil {
		return x.LastBlockHash
	}
	return ""
}

func (x *StatusResponse) GetTotalBlocks() int32 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

var File_proto_aether_proto protoreflect.FileDescriptor

const file_proto_aether_proto_rawDesc = "" +
	"\n" +
	"\x12proto/aether.proto\x12\x06aether\"5\n" +
	"\vDataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"E\n" +
	"\fDataResponse\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\a\n" +
	"\x05Empty\"z\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x01 \x01(\x05R\tpeerCount\x12&\n" +
	"\x0flast_block_hash\x18\x02 \x01(\tR\rlastBlockHash\x12!\n" +
	"\ftotal_blocks\x18\x03 \x01(\x05R\vtotalBlocks2\x80\x01\n" +
	"\rAetherService\x127\n" +
	"\n" +
	"SubmitData\x12\x13.aether.DataRequest\x1a\x14.aether.DataResponse\x126\n" +
	"\rGetNodeStatus\x12\r.aether.Empty\x1a\x16.aether.StatusResponseB'Z%github.com/JullMol/aether-chain/protob\x06proto3"

var (
	file_proto_aether_proto_rawDescOnce sync.Once
	file_proto_aether_proto_rawDescData []byte
)

func file_proto_aether_proto_rawDescGZIP() []byte {
	file_proto_aether_proto_rawDescOnce.Do(func() {
		file_proto_aether_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)))
	})
	return file_proto_aether_proto_rawDescData
}

var file_proto_aether_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_aether_proto_goTypes = []any{
	(*DataRequest)(nil),    // 0: aether.DataRequest
	(*DataResponse)(nil),   // 1: aether.DataResponse
	(*Empty)(nil),          // 2: aether.Empty
	(*StatusResponse)(nil), // 3: aether.StatusResponse
}
var file_proto_aether_proto_depIdxs = []int32{
	0, // 0: aether.AetherService.SubmitData:input_type -> aether.DataRequest
	2, // 1: aether.AetherService.GetNodeStatus:input_type -> aether.Empty
	1, // 2: aether.AetherService.SubmitData:output_type -> aether.DataResponse
	3, // 3: aether.AetherService.GetNodeStatus:output_type -> aether.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_aether_proto_init() }
func file_proto_aether_proto_init() {
	if File_proto_aether_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aether_proto_goTypes,
		DependencyIndexes: file_proto_aether_proto_depIdxs,
		MessageInfos:      file_proto_aether_proto_msgTypes,
	}.Build()
	File_proto_aether_proto = out.File
	file_proto_aether_proto_goTypes = nil
	file_proto_aether_proto_depIdxs = nil
}
