// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/aether.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AetherService_SubmitData_FullMethodName    = "/aether.AetherService/SubmitData"
	AetherService_GetNodeStatus_FullMethodName = "/aether.AetherService/GetNodeStatus"
)

// AetherServiceClient is the client API for AetherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AetherServiceClient interface {
	SubmitData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	GetNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type aetherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAetherServiceClient(cc grpc.ClientConnInterface) AetherServiceClient {
	return &aetherServiceClient{cc}
}

func (c *aetherServiceClient) SubmitData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, AetherService_SubmitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aetherServiceClient) GetNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AetherService_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AetherServiceServer is the server API for AetherService service.
// All implementations must embed UnimplementedAetherServiceServer
// for forward compatibility.
type AetherServiceServer interface {
	SubmitData(context.Context, *DataRequest) (*DataResponse, error)
	GetNodeStatus(context.Context, *Empty) (*StatusResponse, error)
	mustEmbedUnimplementedAetherServiceServer()
}

// UnimplementedAetherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAetherServiceServer struct{}

func (UnimplementedAetherServiceServer) SubmitData(context.Context, *DataRequest) (*DataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitData not implemented")
}
func (UnimplementedAetherServiceServer) GetNodeStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedAetherServiceServer) mustEmbedUnimplementedAetherServiceServer() {}
func (UnimplementedAetherServiceServer) testEmbeddedByValue()                       {}

// UnsafeAetherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AetherServiceServer will
// result in compilation errors.
type UnsafeAetherServiceServer interface {
	mustEmbedUnimplementedAetherServiceServer()
}

func RegisterAetherServiceServer(s grpc.ServiceRegistrar, srv AetherServiceServer) {
	// If the following call panics, it indicates UnimplementedAetherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AetherService_ServiceDesc, srv)
}

func _AetherService_SubmitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AetherServiceServer).SubmitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AetherService_SubmitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AetherServiceServer).SubmitData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AetherService_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AetherServiceServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AetherService_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AetherServiceServer).GetNodeStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AetherService_ServiceDesc is the grpc.ServiceDesc for AetherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AetherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aether.AetherService",
	HandlerType: (*AetherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitData",
			Handler:    _AetherService_SubmitData_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _AetherService_GetNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aether.proto",
}
